### ISSUE TITLE
为什么自己创建的文章在博客里无法放大显示？点击放大按钮没有反应。

### ISSUE THREAD

**Issue by Leo-2019** [MuZhou233/Morecho-Jekyll#7]

**Comment by MuZhou233** [comment]
请贴一下可以复现这个问题的网页链接

**Comment by Leo-2019** [comment]
https://leo-2019.github.io/

**Comment by MuZhou233** [comment]
应该是因为你有部分图片元素没有alt属性也就是markdown里的图片注释，你可以检查一下，抱歉目前没有精力修复

**Comment by Leo-2019** [comment]
还发现了一个问题：图片的描述是居中显示的，但是图片却不是居中的。🤣

**Comment by MuZhou233** [comment]
事实上我更换到typecho之后这个版本就没有再维护了，[typecho版本](https://github.com/MuZhou233/Morecho-Typecho)的用户比较多，bug比较少，或者你可以试试我现在正在用的[docusaurus](https://docusaurus.io/zh-CN/docs) （不过这俩都更折腾🤣
